config/routes.rb
Rails.application.routes.draw do
# namespace :admin do
#   get 'users/index'
#   get 'users/show'
#   get 'users/create'
#   get 'users/update'
#   get 'users/new'
#   get 'users/destroy'
#   get 'users/edit'
# end
  get 'reviews/new'
  get 'reviews/create'

  get 'sessions/new'
  get 'sessions/create'

  get 'users/new'
  get 'users/create'

  resources :movies do 
    resources :reviews, only: [:new, :create]
  end

  resources :users, only: [:new, :create]
  resource :user, only: [:show]
  resource :session, only: [:new, :create, :destroy]

  namespace :admin do
    resources :users 
  end
  root to: 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  scope :by_title, -> title_query {where('title LIKE ?', "%#{title_query}%")}
  scope :by_director, -> director_query {where('director LIKE ?', "%#{director_query}%")}
  scope :by_duration, -> runtime do
    duration = case runtime  
               when 'less than 90' 
                 'runtime_in_minutes < 90' 
               when 'between 90 & 120'
                 'runtime_in_minutes > 90 AND runtime_in_minutes < 120' 
               when 'greater than 120'
                 'runtime_in_minutes > 120' 
               else
                 nil
               end

    where(duration)
  end
  validates :title, presence: true
  validates :director, presence: true
  validates :runtime_in_minutes, presence: true, numericality: {only_integer: true}
  validates :description, presence: true
  #validates :poster_image_url, presence: true
  validates :release_date, presence: true
  validate :release_date_is_in_the_past

  has_many :reviews

  mount_uploader :image, AvatarUploader  

  def review_average
   reviews.length.zero? ? nil : reviews.sum(:rating_out_of_ten)/reviews.size 
  end
    
  protected

  def release_date_is_in_the_past
    if release_date.present?
      errors.add(:release_date, 'should be in the past') if release_date > Date.today
    end
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie

  validates :user, presence: true
  validates :movie, presence: true
  
  validates :text, presence: true

  validates :rating_out_of_ten, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to:10}
end

app/models/user.rb
class User < ActiveRecord::Base

  validates :email, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, numericality: {greater_than: 7}

  paginates_per 50

  has_secure_password
  has_many :reviews 

  def full_name
    "#{firstname} #{lastname}"
  end

  protected

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :admin_access_check
  def index
    @users = User.order(:id).page(params[:page]).per(8)
  end

  def show
    @user = User.find(params[:id].to_i)
  end

  def create
  end

  def update
  end

  def new
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      UserMailer.user_destroyed_email(@user).deliver_now
      flash[:notice] = 'Account was destroyed' #refactor later
      redirect_to admin_users_path 
    else
      flash[:error] = 'Account was not destroyed'
      redirect_to admin_user(@user)
    end
  end

  def edit
  end

  protected

  def admin_access_check 
    unless current_user.is_admin?
      flash[:error] = "You must be an admin to access this page"
      redirect_to movies_path 
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  
  def restrict_access
    if !current_user
      flash[:alert] = "You must log in."
      redirect_to new_session_path
    end
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController 
  def index 
    #@movies = Movie.by_title(params[:title_query]).by_director(params[:director_query]).by_duration(params[:runtime])
    @movies = Movie.all
    @movies = @movies.where("title LIKE ? OR director LIKE ?", "%#{params[:query]}%", "%#{params[:query]}%") if params[:query]
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path, notice: "#{@movie.title} was submitted successfully!"
    else
      render :new
    end
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movie_params)
      redirect_to movies_path
    else
      render :edit
    end
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path 
  end

  protected
  
  def movie_params
    params.require(:movie).permit(:title, :director, :runtime_in_minutes, :description, :poster_image_url, :release_date, :image)
  end
 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_movies
  before_filter :restrict_access

  def new
    @review = @movie.reviews.build
  end

  def create
    @review = @movie.reviews.build(review_params)
    @review.user_id = current_user.id

    if @review.save
      redirect_to @movie, notice: "Review created successfully"
    else
      render :new
    end
  end

  protected
  def load_movies
    @movie = Movie.find(params[:movie_id])
  end
  def review_params
    params.require(:review).permit(:text, :rating_out_of_ten)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to movies_path, notice: "#{user.firstname} has successfully logged in!"
    else
      flash[:error] = 'Email and password do not match.' 
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to movies_path, notice: "Sayonara!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params) 
    if @user.save
      session[:user_id] = @user.id
      redirect_to movies_path, notice: "Account has succesfully been created!"
    else 
      flash.now[:alert] = "Log in failed..."
      render :new
    end
  end

  def show 
    @user = User.find(current_user.id)
  end
  protected 

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :firstname, :lastname)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def formatted_date(date)
    date.strftime("%b %d, %Y")
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/create.html.erb
<h1>Admin::Users#create</h1>
<p>Find me in app/views/admin/users/create.html.erb</p>

app/views/admin/users/destroy.html.erb
<h1>Admin::Users#destroy</h1>
<p>Find me in app/views/admin/users/destroy.html.erb</p>

app/views/admin/users/edit.html.erb
<h1>Admin::Users#edit</h1>
<p>Find me in app/views/admin/users/edit.html.erb</p>

app/views/admin/users/index.html.erb
<h1>USERS</h1>
<%=paginate @users%>
<% if @users %>
  <table border='1' style='width:100%'>
    <th>ID</th>
    <th>Email</th>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Profile</th>
  <% @users.each do |user| %>
  
    <tr>
      <td><%=user.id%></td> 
      <td><%=user.email%></td>
      <td><%=user.firstname%></td>
      <td><%=user.lastname%></td>
      <td><%=link_to "Click", admin_user_path(user.id)%></td>
    <tr>
  <%end%> 
<%end%>

app/views/admin/users/new.html.erb
<h1>Admin::Users#new</h1>
<p>Find me in app/views/admin/users/new.html.erb</p>

app/views/admin/users/show.html.erb
<h1>Admin</h1>
<h2><%=@user.full_name%>(<%=link_to 'edit', edit_admin_user_url%>)(<%=link_to 'delete', "/admin/users/#{@user.id}", :method => :delete, :'data-confirm' => 'You sure?' %>)</h2>
<p>Email: <%=@user.email%></p>
<p>Join Date: <%=@user.created_at%></p>
<p>Last Edited: <%=@user.updated_at%></p>

app/views/admin/users/update.html.erb
<h1>Admin::Users#update</h1>
<p>Find me in app/views/admin/users/update.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  
  <div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href=<%=movies_path%>>Rotten Mangoes</a>
    </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%=movies_path%>">Movies<span class="sr-only">(current)</span></a></li>
        <li><a href=<%=new_movie_path%>>Post Movie</a></li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <%=form_tag movies_path, method: 'GET' do %>
            <%=text_field_tag :query, nil, placeholder: 'Director or Movie Title'%>
        <button type="submit" class="btn btn-default">Submit</button>
        </div>
        <%end%>
      </form>
      <ul class="nav navbar-nav navbar-right">
      <%if current_user%>
        <%if current_user.is_admin?%>
          <li><a href=<%=admin_users_path%>>All Users</a></li>
        <%end%>
        <li><%=link_to current_user.full_name, user_path(current_user)%></li> 
        <li><%= link_to "Log Out", session_path("current"), method: :delete%></li>
      <%else%>
        <li><%=link_to "Log In", new_session_path%></li>
        <li><%= link_to "Sign Up", new_user_path%></li> 
      <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RottenMangoes</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%=render 'layouts/navbar'%> 
    <div class='col-md-6 col-md-offset-3'>
      <%flash.each do |key, value|%>
        <%=content_tag(:div, value)%>
      <%end%>
      <%= yield %>
    </div>
  </body>
</html>

app/views/movies/_form.html.erb
<%if @movie.errors.full_messages%>
  <ul>
    <%@movie.errors.full_messages.each do |error|%>
      <li><%=error%></li>
    <%end%>
  </ul>
<%end%>
    
<%=form_for @movie, :html => {:multipart => true} do |f|%>
  <div class='form-group'> 
    <div>
      <%=f.label 'title'%><br>
      <%=f.text_field 'title'%>
    </div>
    <div>
      <%=f.label 'director'%><br>
      <%=f.text_field 'director'%> </div>
    <div>
      <%=f.label 'runtime_in_minutes'%><br>
      <%=f.number_field 'runtime_in_minutes'%>
    </div>
    <div>
      <%=f.label 'description'%><br>
      <%=f.text_area 'description'%>
    </div>
    <div>
      <%=f.label :image%>
      <%=f.file_field :image%> 
    </div>
    <div>
      <%=f.label 'release_date'%>
      <%=f.date_field 'release_date'%>
    </div>
    <div>
      <%=button_tag(type: 'submit', class: 'btn btn-primary') do%>
          <i class='icon-ok icon-white'></i>
          Submit
      <%end%>
    </div>
  </div>
<%end%>

app/views/movies/_movie.html.erb
<%@movies.each do |movie|%>
  <div>
    <h3>
      <a href=<%=movie_path(movie.id)%>><%=movie.title%></a>
    </h3>
    <p><small>Directed by <%=movie.director%></small></p>
  <%if movie.review_average%>
    <%=movie.review_average%>/10
  <%else%>
    <%="No reviews yet"%>
  <%end%>
    <hr>
  </div>
<%end%>

app/views/movies/_search_form.html.erb
<div>
  <hr>
  <%=form_tag movies_path, method: 'GET' do %>
    <%= text_field_tag :title_query, nil, placeholder: 'Search movie title'%><br> 
    <%= text_field_tag :director_query, nil, placeholder: 'Search director name'%><br>
    
    
    <%= select_tag 'runtime',
      "<option value=nil>Select runtime</option>
      <option value = 'less than 90'>Under 90 mins</option>
      <option value = 'between 90 & 120'>Between 90 and 120 mins</option>
      <option value = 'greater than 120'>Over 120 mins</option>".html_safe, :id => 'runtime'%>
    <%=button_tag(type:'submit', class: 'btn btn-primary') do%>
      <i class='icon-ok icon-white'></i> Search
    <%end%>

  <%end%>
  <hr>
</div>

app/views/movies/edit.html.erb
<h2>Edit movie post</h2>
<%=render 'form'%>

app/views/movies/index.html.erb
<div class='row'>
  <h1 class=>Movies</h1>
  <%=render 'search_form'%>
  <%=render 'movie'%>
</div>

app/views/movies/new.html.erb
<h2>Create a movie post!</h2>
<%=render 'form'%>

app/views/movies/show.html.erb
<div>
  <p><%=link_to "Back to movies", movies_path%></p>

  <h2><%=@movie.title%>(<%=link_to"edit", edit_movie_path(@movie)%>)(<%=link_to "delete", movie_path(@movie), :method => :delete, :'data-confirm' => "You sure?"%>)</h2>
  <p><small>Director: <%=@movie.director%></small></p>
  <%if @movie.poster_image_url%>
    <img src=<%=@movie.poster_image_url%>/>
  <%else%>
    <%=image_tag @movie.image.url%> <p>Release Date: <%=formatted_date(@movie.release_date)%></p> <!--TODO: limit photo size--> 
  <%end%> 
  <p>Length: <%=@movie.runtime_in_minutes%> mins</p>
  <p>Description: <%=@movie.description%></p>
  <%if @movie.review_average%> 
    <h3>Rating: <%=@movie.review_average%>/10</h3>
  <%else%>
    <%="No reviews yet"%>
  <%end%>
</div>

<hr>

<div>
  <h3>Reviews of <em><%=@movie.title%></em></h3>
  <%if current_user%>
    <%@movie.reviews.each do |review|%>
      <p><%=review.text%></p>
      <p><%=review.rating_out_of_ten%>/10</p>
      <small>- <%=link_to review.user.full_name, user_path(review.user)%></small><br/>
      <br>
    <%end%>
    <p><%=link_to "Write a review!", new_movie_review_path(@movie)%></p>
  <%else%>
    <p>Please <%=link_to "log in", new_session_path%> to see reviews and add your own.</p>
  <%end%>
</div>

app/views/reviews/new.html.erb
<%=link_to "Back to Movie", movie_path(@movie)%><br>
  
<h2>Write a review of <em><%=@movie.title%></em></h2>

<%=form_for([@movie,@review]) do |f|%>
  <%if @review.errors.any?%> 
    <div>
      <%=pluralize(@review.errors.count, 'error')%> prevented review form being saved:
      <ul>
        <%@review.errors.full_messages.each do |msg|%>
          <li><%=msg%></li>
        <%end%>
      </ul> 
    </div>
  <%end%>

  <div>
    <%=f.label :text%><br>
    <%=f.text_area "text"%>
  </div>
  <div>
    <%=f.label :rating_out_ten%><br>
    <%=f.number_field :rating_out_of_ten %>
  </div>
  <div>
    <br>
    <%=button_tag(type:'submit', class: 'btn btn-primary') do%>
      <i class='icon-ok icon-white'></i> Search
    <%end%>
  </div>
<%end%>   

app/views/users/_form.html.erb
<% if @user.errors %>
  <div>
    <%@user.errors.full_messages.each do |msg|%>
      <li><%=msg%></li>
    <%end%>
  </div>
<%end%> 
<%=form_for @user do |f|%>
  <div class='form-group'>
    <div>
      <%=f.label 'firstname'%><br>
      <%=f.text_field 'firstname'%>
    </div>
    <div>
      <%=f.label 'lastname'%><br>
      <%=f.text_field 'lastname'%>
    </div>
    <div>
      <%=f.label 'email'%><br>
      <%=f.text_field 'email'%>
    </div>
    <div>
      <%=f.label 'password'%><br>
      <%=f.password_field 'password'%>
    </div>
    <div>
      <%=f.label 'password_confirmation'%><br>
      <%=f.password_field 'password_confirmation'%>
    </div>
    <hr>
    <div>
        <%=button_tag(type: 'submit', class: 'btn btn-primary') do%>
            <i class='icon-ok icon-white'></i>
            Submit
        <%end%>
    </div>
  </div>
<%end%>

app/views/users/create.html.erb
<h1>Sign up</h1>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%=render 'form'%>

app/views/users/show.html.erb
<h1><%=@user.full_name%>
<%if current_user.is_admin?%>
  (<%=link_to 'edit', :method => :edit%>)
  (<%=link_to 'delete', "/admin/users/#{@user.id}", :method => :delete, :'data-confirm' => 'You sure?' %>)
<%end%>
</h1>
<p>Email: <%=@user.email%></p>
<p>Joined at: <%=@user.created_at%></p> 
<hr>
<h2>My Reviews</h2>
<hr>
<%@user.reviews.each do |review|%>
  <h4><%=link_to review.movie.title, movie_path(review.movie)%></h4>
  <p><%=review.text%></p>
  <p><%=review.rating_out_of_ten%>/10</p>
  <hr>
<%end%>